In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
import torch

import warnings
warnings.filterwarnings("ignore")


fruits = pd.read_table('./fruits_data_with_colors.txt')

In [2]:
fruits.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [3]:
fruits

fruit_label fruit_name     fruit_subtype  mass  width  height  color_score
0             1      apple      granny_smith   192    8.4     7.3         0.55
1             1      apple      granny_smith   180    8.0     6.8         0.59
2             1      apple      granny_smith   176    7.4     7.2         0.60
3             2   mandarin          mandarin    86    6.2     4.7         0.80
4             2   mandarin          mandarin    84    6.0     4.6         0.79
5             2   mandarin          mandarin    80    5.8     4.3         0.77
6             2   mandarin          mandarin    80    5.9     4.3         0.81
7             2   mandarin          mandarin    76    5.8     4.0         0.81
8             1      apple          braeburn   178    7.1     7.8         0.92
9             1      apple          braeburn   172    7.4     7.0         0.89
10            1      apple          braeburn   166    6.9     7.3         0.93
11            1      apple          braeburn   172    7.1     7.6         0.92
12            1      apple          braeburn   154    7.0     7.1         0.88
13            1      apple  golden_delicious   164    7.3     7.7         0.70
14            1      apple  golden_delicious   152    7.6     7.3         0.69
15            1      apple  golden_delicious   156    7.7     7.1         0.69
16            1      apple  golden_delicious   156    7.6     7.5         0.67
17            1      apple  golden_delicious   168    7.5     7.6         0.73
18            1      apple       cripps_pink   162    7.5     7.1         0.83
19            1      apple       cripps_pink   162    7.4     7.2         0.85
20            1      apple       cripps_pink   160    7.5     7.5         0.86
21            1      apple       cripps_pink   156    7.4     7.4         0.84
22            1      apple       cripps_pink   140    7.3     7.1         0.87
23            1      apple       cripps_pink   170    7.6     7.9         0.88
24            3     orange     spanish_jumbo   342    9.0     9.4         0.75
25            3     orange     spanish_jumbo   356    9.2     9.2         0.75
26            3     orange     spanish_jumbo   362    9.6     9.2         0.74
27            3     orange  selected_seconds   204    7.5     9.2         0.77
28            3     orange  selected_seconds   140    6.7     7.1         0.72
29            3     orange  selected_seconds   160    7.0     7.4         0.81
30            3     orange  selected_seconds   158    7.1     7.5         0.79
31            3     orange  selected_seconds   210    7.8     8.0         0.82
32            3     orange  selected_seconds   164    7.2     7.0         0.80
33            3     orange      turkey_navel   190    7.5     8.1         0.74
34            3     orange      turkey_navel   142    7.6     7.8         0.75
35            3     orange      turkey_navel   150    7.1     7.9         0.75
36            3     orange      turkey_navel   160    7.1     7.6         0.76
37            3     orange      turkey_navel   154    7.3     7.3         0.79
38            3     orange      turkey_navel   158    7.2     7.8         0.77
39            3     orange      turkey_navel   144    6.8     7.4         0.75
40            3     orange      turkey_navel   154    7.1     7.5         0.78
41            3     orange      turkey_navel   180    7.6     8.2         0.79
42            3     orange      turkey_navel   154    7.2     7.2         0.82
43            4      lemon    spanish_belsan   194    7.2    10.3         0.70
44            4      lemon    spanish_belsan   200    7.3    10.5         0.72
45            4      lemon    spanish_belsan   186    7.2     9.2         0.72
46            4      lemon    spanish_belsan   216    7.3    10.2         0.71
47            4      lemon    spanish_belsan   196    7.3     9.7         0.72
48            4      lemon    spanish_belsan   174    7.3    10.1         0.72
49            4      lemon           unknown   132    

In [4]:
fruits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fruit_label    59 non-null     int64  
 1   fruit_name     59 non-null     object 
 2   fruit_subtype  59 non-null     object 
 3   mass           59 non-null     int64  
 4   width          59 non-null     float64
 5   height         59 non-null     float64
 6   color_score    59 non-null     float64
dtypes: float64(3), int64(2), object(2)
memory usage: 3.4+ KB


In [5]:
fruits.shape

(59, 7)

In [6]:
from sklearn.preprocessing import MinMaxScaler

X = fruits[['mass', 'width', 'height', 'color_score']]
y = fruits['fruit_label'] - 1

ss = MinMaxScaler() 
X_scaled = ss.fit_transform(X)
X = X_scaled
y = y.to_numpy()

In [7]:
X = torch.from_numpy(X).type(torch.float)
y = torch.from_numpy(y).type(torch.LongTensor)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [9]:
print(X[:10], y[:10])

tensor([[0.4056, 0.6842, 0.5077, 0.0000],
        [0.3636, 0.5789, 0.4308, 0.1053],
        [0.3497, 0.4211, 0.4923, 0.1316],
        [0.0350, 0.1053, 0.1077, 0.6579],
        [0.0280, 0.0526, 0.0923, 0.6316],
        [0.0140, 0.0000, 0.0462, 0.5789],
        [0.0140, 0.0263, 0.0462, 0.6842],
        [0.0000, 0.0000, 0.0000, 0.6842],
        [0.3566, 0.3421, 0.5846, 0.9737],
        [0.3357, 0.4211, 0.4615, 0.8947]]) tensor([0, 0, 0, 1, 1, 1, 1, 1, 0, 0])


In [10]:
y

tensor([0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [11]:
from torch import nn

# Build model
class Classificator(nn.Module):
    def __init__(self, input_features, output_features, hidden_units=8):
        """Initializes all required hyperparameters for a multi-class classification model.

        Args:
            input_features (int): Number of input features to the model.
            out_features (int): Number of output features of the model
              (how many classes there are).
            hidden_units (int): Number of hidden units between layers, default 8.
        """
        super().__init__()
        self.linear_layer_stack = nn.Sequential(
            nn.Linear(in_features=input_features, out_features=hidden_units),
            nn.Tanh(),
            nn.Linear(in_features=hidden_units, out_features=hidden_units),
            nn.Tanh(),
            nn.Linear(in_features=hidden_units, out_features=output_features),
        )
    
    def forward(self, x):
        return self.linear_layer_stack(x)

model = Classificator(input_features=4, 
                    output_features=4, 
                    hidden_units=8)
model

BlobModel(
  (linear_layer_stack): Sequential(
    (0): Linear(in_features=4, out_features=8, bias=True)
    (1): Tanh()
    (2): Linear(in_features=8, out_features=8, bias=True)
    (3): Tanh()
    (4): Linear(in_features=8, out_features=4, bias=True)
  )
)

In [12]:
# Create loss and optimizer
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), 
                            lr=0.3)

In [13]:
model(X_train)[0].shape

torch.Size([4])

In [14]:
# Make prediction logits with model
y_logits = model(X_test)

# Perform softmax calculation on logits across dimension 1 to get prediction probabilities
y_pred_probs = torch.softmax(y_logits, dim=1) 
print(y_logits[:5])
print(y_pred_probs[:5])

tensor([[-0.0915, -0.0208, -0.0510, -0.0040],
        [-0.1337, -0.1476, -0.0260,  0.0485],
        [-0.1286, -0.1275, -0.0523,  0.0307],
        [-0.1455, -0.1427, -0.0242,  0.0553],
        [-0.0948, -0.2250, -0.0169,  0.0562]], grad_fn=<SliceBackward0>)
tensor([[0.2378, 0.2552, 0.2476, 0.2595],
        [0.2326, 0.2294, 0.2590, 0.2790],
        [0.2351, 0.2354, 0.2538, 0.2757],
        [0.2297, 0.2303, 0.2593, 0.2808],
        [0.2426, 0.2130, 0.2623, 0.2821]], grad_fn=<SliceBackward0>)


In [15]:
y_logits.shape, y_pred_probs.shape

(torch.Size([15, 4]), torch.Size([15, 4]))

In [16]:
# Fit the model
torch.manual_seed(42)

# Set number of epochs
epochs = 10000

for epoch in range(epochs):
    ### Training
    model.train()

    # 1. Forward pass
    y_logits = model(X_train)
    y_pred = torch.softmax(y_logits, dim=1)
    
    # 2. Calculate loss and accuracy
    loss = loss_fn(y_logits, y_train)

    # 3. Optimizer zero grad
    optimizer.zero_grad()

    # 4. Loss backwards
    loss.backward()

    # 5. Optimizer step
    optimizer.step()

    ### Testing
    model.eval()
    with torch.inference_mode():
      # 1. Forward pass
      test_logits = model(X_test)
      test_pred = torch.softmax(test_logits, dim=1)
      # 2. Calculate test loss and accuracy
      test_loss = loss_fn(test_logits, y_test)

    # Print out what's happening
    if epoch % 1000 == 0:
        print(f"Epoch: {epoch} | Loss: {loss:.5f} | Test Loss: {test_loss:.5f}") 

Epoch: 0 | Loss: 1.37851 | Test Loss: 1.36921
Epoch: 1000 | Loss: 0.20869 | Test Loss: 0.47836
Epoch: 2000 | Loss: 0.00695 | Test Loss: 0.42459
Epoch: 3000 | Loss: 0.00260 | Test Loss: 0.47473
Epoch: 4000 | Loss: 0.00156 | Test Loss: 0.50138
Epoch: 5000 | Loss: 0.00110 | Test Loss: 0.51959
Epoch: 6000 | Loss: 0.00084 | Test Loss: 0.53345
Epoch: 7000 | Loss: 0.00068 | Test Loss: 0.54462
Epoch: 8000 | Loss: 0.00057 | Test Loss: 0.55395
Epoch: 9000 | Loss: 0.00049 | Test Loss: 0.56196


In [17]:
# Make predictions
model.eval()
with torch.inference_mode():
    y_logits = model(X_test)

# View the first 10 predictions
y_logits[:10]

tensor([[ 4.9089, -6.5004,  7.3973, -5.4515],
        [-3.6757, -2.9807,  6.4118,  0.2854],
        [-2.6974, -5.8413, -1.6916,  8.7484],
        [-5.7428, -1.1673,  3.1627,  3.3718],
        [11.8573, -2.1183, -0.2930, -9.4498],
        [ 6.7058, -5.1187, -4.2598,  1.8462],
        [ 8.7389, -3.8642,  1.2822, -6.1813],
        [-3.4958, -7.1316,  0.0709,  9.1993],
        [-4.7278, -2.5552, 10.1942, -2.4673],
        [10.6563, -0.7897, -0.3652, -9.4249]])

In [18]:
import requests
from pathlib import Path 

# Download helper functions from Learn PyTorch repo (if not already downloaded)
if Path("helper_functions.py").is_file():
  print("helper_functions.py already exists, skipping download")
else:
  print("Downloading helper_functions.py")
  request = requests.get("https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/helper_functions.py")
  with open("helper_functions.py", "wb") as f:
    f.write(request.content)

from helper_functions import plot_predictions, plot_decision_boundary

helper_functions.py already exists, skipping download


In [19]:
def accuracy_fn(y_true, y_pred):
  correct = torch.eq(y_true, y_pred).sum().item()
  acc = (correct/len(y_pred)) * 100
  return acc

In [20]:
# Turn predicted logits in prediction probabilities
y_pred_probs = torch.softmax(y_logits, dim=1)

# Turn prediction probabilities into prediction labels
y_preds = y_pred_probs.argmax(dim=1)

# Compare first 10 model preds and test labels
print(f"Predictions: {y_preds}\nLabels: {y_test}")
print(f"Test accuracy: {accuracy_fn(y_true=y_test, y_pred=y_preds)}%")

Predictions: tensor([2, 2, 3, 3, 0, 0, 0, 3, 2, 0, 1, 0, 2, 2, 2])
Labels: tensor([2, 2, 3, 2, 0, 0, 2, 3, 2, 0, 1, 0, 2, 2, 2])
Test accuracy: 86.66666666666667%
